# Generated by Django 4.2.1 on 2023-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_email_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='books',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='api.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_to_complete',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progress',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='topic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
